name: Actions environment inspector
on: [push]
jobs:
  Do-Things:
    runs-on: ubuntu-latest
    steps:
      - run: dpkg -l
      - run: snap list
      - run: snap changes
      - run: w
      - run: uptime
      - run: sudo snap find this-is-wgrant-from-github
      - run: uname -a
      - run: ls -l /var/lib/snapd/snaps
      - run: sudo snap known serial
      - run: echo "Are we all clones?"
      - run: cat /proc/mounts
      - run: sudo lshw
